---
title: "Data Import"
output: github_document
---

## Data Import: CSVs

Let's import data usign the readr package 

```{r}
library(tidyverse)
library(dplyr)
litters_df <- read_csv("data/FAS_litters.csv")
litters_df <- janitor::clean_names(litters_df) #cleans the name of the functions 

head(litters_df)
tail(litters_df)

```

```{r, eval=FALSE}
view(litters_df)

```

```{r}
skimr::skim(litters_df) #quick summary of the dataset 

```

"read_csv" options 

```{r}
read_csv("data/FAS_litters.csv", na = c("", "NA", "999", 999, 88)) #how to remane and standardize NA 

litters_df

```

## Other file formats 

We need to read in an excel spread sheet 

```{r}
library(readxl)
mlb_df <- read_excel("data/mlb11.xlsx")
lotr_words_df <- read_excel("data/LotR_Words.xlsx", range = "B3:D6")

```

## Still more file formats 

Read in a SAS dataset 

```{r}
library(haven) #used to upload SAS data 
pulse_df <- read_sas("data/public_pulse_data.sas7bdat")


```

##Data export 

```{r}
write_csv(litters_df, "data/litters")

```

##Why not base R?

```{r}
